# Site settings
title: javadev.org
description: Website about java development. Java SE, Java EE
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://javadev.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
